@enum TipoCTES begin
    GLUCEMIAS = 2
    TA_SISTOLICA = 3
    TA_DISTOLICA = 4
    FRECUENCIA_CARDIACA = 5
    SATO2 = 6
    DIURESIS = 7
    TEMPERATURA = 8
end

export  TipoCTES


@enum TipoAnalitica begin
    PCR_PROTEINA_C_REACTIVA = 1
    PROCALCITONINA = 2
    TP_TIEMPO_PROTROMBINA = 3
    INR = 4
    DIMERO_D = 5
    ALBUMINA_SERICA = 6
    CREATININA_SERICA = 7
    BUN_NITROGENO_UREICO = 8
    TRANSAMINASAS_GPT = 9
    TRANSAMINASAS_GOT = 10
    BILIRRUBINA_TOTAL = 11
    LACTATO = 12
    TROPONINA = 13
    BNP_NT_PROBNP = 14
    LEUCOCITOS = 15
    HEMATIES = 16
    HEMOGLOBINA = 17
    HEMATOCRITO = 18
    RDW = 19
    PLAQUETAS = 20
    VPM = 21
    NEUTROFILOS = 22
    LINFOCITOS = 23
    EOSINOFILOS = 24
    NEUTROFILOS_ABSOLUTOS = 25
    LINFOCITOS_ABSOLUTOS = 26
    EOSINOFILOS_ABSOLUTOS = 27
    VSG = 28
end

export TipoAnalitica