# CONSTANTES
const GLUCEMIAS = 2
const TA_SISTOLICA = 3
const TA_DISTOLICA = 4
const FRECUENCIA_CARDIACA = 5
const SATO2 = 6
const DIURESIS = 7
const TEMPERATURA = 8

export GLUCEMIAS, TA_SISTOLICA, TA_DISTOLICA, FRECUENCIA_CARDIACA, SATO2, DIURESIS, TEMPERATURA


#Variables derivadas de CONSTANTES
#Se definen en NEGATIVO para evitar colisiones futuras
const DIURESIS24H = -1  
const SHOCK_INDEX = -2
const TA_MEDIA = -3
const M_SHOCK_INDEX = -4

export DIURESIS24H, SHOCK_INDEX, TA_MEDIA, M_SHOCK_INDEX


# LAB_RESULTADOS
const PCR_PROTEINA_C_REACTIVA = 1
const PROCALCITONINA = 2
const TP_TIEMPO_PROTROMBINA = 3
const INR = 4
const DIMERO_D = 5
const ALBUMINA_SERICA = 6
const CREATININA_SERICA = 7
const BUN_NITROGENO_UREICO = 8
const TRANSAMINASAS_GPT = 9
const TRANSAMINASAS_GOT = 10
const BILIRRUBINA_TOTAL = 11
const LACTATO = 12
const TROPONINA = 13
const BNP_NT_PROBNP = 14
const LEUCOCITOS = 15
const HEMATIES = 16
const HEMOGLOBINA = 17
const HEMATOCRITO = 18
const RDW = 19
const PLAQUETAS = 20
const VPM = 21
const NEUTROFILOS = 22
const LINFOCITOS = 23
const EOSINOFILOS = 24
const NEUTROFILOS_ABSOLUTOS = 25
const LINFOCITOS_ABSOLUTOS = 26
const EOSINOFILOS_ABSOLUTOS = 27
const VSG = 28

export PCR_PROTEINA_C_REACTIVA, PROCALCITONINA, TP_TIEMPO_PROTROMBINA, INR, DIMERO_D, ALBUMINA_SERICA, CREATININA_SERICA, BUN_NITROGENO_UREICO, TRANSAMINASAS_GPT, TRANSAMINASAS_GOT, BILIRRUBINA_TOTAL, LACTATO, TROPONINA, BNP_NT_PROBNP, LEUCOCITOS, HEMATIES, HEMOGLOBINA, HEMATOCRITO, RDW, PLAQUETAS, VPM, NEUTROFILOS, LINFOCITOS, EOSINOFILOS, NEUTROFILOS_ABSOLUTOS, LINFOCITOS_ABSOLUTOS, EOSINOFILOS_ABSOLUTOS, VSG