@enum Tabla begin
    EPISODIOS
    CODIFICACION
    VALENF
    TRASLADOS
    INTERCONSULTAS
    INTERVENCIONES
    CONSTANTES
    LABORATORIO
    LAB_RESULTADOS
end

export Tabla, EPISODIOS, CODIFICACION, VALENF, TRASLADOS, INTERCONSULTAS, INTERVENCIONES, CONSTANTES, LABORATORIO, LAB_RESULTADOS